name: Release

on:
  push:
    tags:
      - 'v*'

permissions: write-all

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
      - name: Build
        id: build
        run: |
          npm install
          npm run build:prod
          zip -r release.zip build
          echo "tag_name=$(git tag --sort version:refname | tail -n 1)" >> $GITHUB_OUTPUT
      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          files: release.zip
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
